baseURL = "http://chuyutian.com"
languageCode = "en-us"
title = "Chuyu Tian"
theme = "ananke"
enableRobotsTXT = true




[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"


[params]
  show_reading_time = false
  background_color_class = "bg-blue"
  textColor = "black"
