baseURL = "http://chuyutian.com"
languageCode = "en-us"
title = "Chuyu Tian"
enableRobotsTXT = true
sectionPagesMenu = "main"


[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"


[params]
  show_reading_time = false
  background_color_class = "garamond bg-dark-green"
  textColor = "garamond black"
  body_classes = "garamond"
  post_content_classes = "garamond"

[markup]
  [markup.images]
    # Enable image processing
    process = true

  
[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Dissertation"
  url = "/dissertation/"
  weight = 2

[[menu.main]]
  name = "CV"
  url = "/cv/"
  weight = 3

[[menu.main]]
  name = "YouTube"
  url = "/youtube/"
  weight = 4

[[menu.main]]
  name = "Contact"
  url = "/contact/"
  weight = 5
