baseURL = "http://chuyutian.com"
languageCode = "en-us"
title = "Chuyu Tian"
theme = "ananke"
enableRobotsTXT = true
sectionPagesMenu = "main"


[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"


[params]
  show_reading_time = false
  background_color_class = "garamond bg-silver"
  textColor = "garamond black"
  body_classes = "garamond"
  post_content_classes = "garamond"